version: '3.4'
services:
  voting:
    image: golang:1.10.0
    container_name: voting.server
    ports:
      - "4000:4000"
    volumes:
      - "$PWD:/app"
  node:
    image: node:9.9.0
    volumes:
      - "$PWD:/app"
