version: '3.4'
services:
  geth:
    image: ethereum/client-go:alpine
    ports:
      - "8545:8545"
  voting:
    image: golang:1.10.0
    ports:
      - "4000:4000"
    volumes:
      - "$PWD:/app"
  node:
    image: node:9.9.0
    volumes:
      - "$PWD:/app"
